name: 'C++ CI/CD'

on:
  push:
    branches:
      - master
      - feature/nosql_storage
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            build-essential \
            libboost-test-dev \
            libgtest-dev \
            protobuf-compiler \
            libprotobuf-dev \
            libgrpc++-dev \
            protobuf-compiler-grpc
      
      - name: Configure CMake
        # Создаем папку build и конфигурируем проект
        run: cmake -DPATCH_VERSION=${{ github.run_number }} \
                   -DCMAKE_BUILD_TYPE=Release \
                   -DWITH_BOOST_TEST=ON -DWITH_GOOGLE_TEST=ON \
                   -DBUILD_EXAMPLES=ON

      - name: Build Project
        run: cmake --build .

      - name: Run Unit Tests
        # Запускаем Google Tests (включая интеграционные сетевые тесты)
        run: cmake --build . --target test

      - name: Run Final Demo Script
        # Запускаем ваш финальный демонстрационный сценарий
        run: |
          chmod +x scripts/run_final_demo.sh
          ./scripts/run_final_demo.sh

      - name: Build Package
        run: cmake --build . --target package

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/')
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./nosql_storage-0.0.${{ github.run_number }}-Linux.deb
          asset_name: nosql_storage-0.0.${{ github.run_number }}-Linux.deb
          asset_content_type: application/vnd.debian.binary-package
